# Generated by Django 6.0.2 on 2026-03-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequestdocument',
            old_name='image',
            new_name='file',
        ),
    ]
