# Generated by Django 6.0.2 on 2026-03-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_rename_image_servicerequestdocument_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
