# Generated by Django 6.0.2 on 2026-03-08 02:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'created_at'], name='devices_dev_user_id_f39231_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['brand'], name='devices_dev_brand_44a749_idx'),
        ),
    ]
